---
apiVersion: v1
kind: Service
metadata:
  name: sre-demo-service
  namespace: dev
  labels:
    app: sre-demo-service
    environment: dev
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 6060
    targetPort: 6060
    protocol: TCP
    name: pprof
  selector:
    app: sre-demo-service
