---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-demo-config
  namespace: prod
  labels:
    app: sre-demo-service
    environment: prod
data:
  ENVIRONMENT: "prod"
  LOG_LEVEL: "warn"
  SERVICE_NAME: "sre-demo-service"
