---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-demo-config
  namespace: qa
  labels:
    app: sre-demo-service
    environment: qa
data:
  ENVIRONMENT: "qa"
  LOG_LEVEL: "info"
  SERVICE_NAME: "sre-demo-service"
